// 실패 문구 한 벌 — 실패 값(FailCode)마다 한 글(ko·en). 설정창·OS 알림이 같은 표를 쓴다. 공용 자리(src/shared)라 DOM·view 를 쓰지 않는다
// - 코드마다 한 글이다. 자리(scope)는 꼴만 다르다 — 교환 배너는 첫 문장을 제목, 나머지를 설명으로 나눈다 (2026-10-04 사용자 결정 "하나로 맞춤", 94 항목 4-7)
// - 글은 worklog/records/code-structure/lanes/fail-text-unify.md 표대로다. 기준은 설정창 문구표, 없던 글은 새로 썼다
// - 표에 없는 글자(실행 때 목록 밖의 코드)가 오면 자리마다 지금 모양의 대체 문구를 쓴다(UNKNOWN)
// 언어는 부르는 쪽이 준다 — shared 는 설정 언어를 모른다. 설정창은 아직 한국어만 쓴다
import type { FailCode } from "./names/online-codes.js";
import { ACCOUNT_RULES as AR } from "./account-rules.js";

export type FailScope = "command" | "trade" | "account" | "mail";
export type FailLang = "ko" | "en";

// 빠진 값은 컴파일 오류다
const FAIL_TEXT: Record<FailCode, { ko: string; en: string }> = {
  ok: { ko: "완료했어요.", en: "Done." },
  error: { ko: "처리하는 중에 오류가 났어요. 잠시 뒤 다시 해 주세요.", en: "Something went wrong. Please try again later." },
  "bad-args": { ko: "요청 내용이 올바르지 않아요.", en: "The request is not valid." },
  "bad-count": { ko: "고를 수 없는 수량이에요.", en: "You can't choose that amount." },
  "bad-value": { ko: "고를 수 없는 값이에요.", en: "You can't choose that value." },
  "bad-cmd": { ko: "보낼 수 없는 명령이에요.", en: "That command can't be sent." },
  "bad-result": { ko: "결과를 읽지 못했어요. 처리됐는지 확인해 주세요.", en: "Couldn't read the result. Please check whether it went through." },
  "send-failed": { ko: "요청을 보내지 못했어요. 잠시 뒤 다시 해 주세요.", en: "Couldn't send the request. Please try again later." },
  timeout: { ko: "응답이 없어요. 처리됐는지 확인해 주세요.", en: "No response. Please check whether it went through." },
  "unknown-cmd": { ko: "알 수 없는 명령이에요.", en: "Unknown command." },
  "no-result": { ko: "결과를 받지 못했어요. 처리됐는지 확인해 주세요.", en: "No result came back. Please check whether it went through." },
  "no-save": { ko: "아직 저장이 없어요. 첫 포켓몬을 고른 뒤 다시 해 주세요.", en: "There's no save yet. Pick your first Pokémon, then try again." },
  "save-failed": { ko: "저장하지 못했어요. 잠시 뒤 다시 해 주세요.", en: "Couldn't save. Please try again later." },
  "not-writer": { ko: "다른 창이 저장을 맡고 있어요. 잠시 뒤 다시 해 주세요.", en: "Another window is handling the save. Please try again later." },
  halted: { ko: "다른 PC 확인이 끝날 때까지 게임이 멈춰 있어요.", en: "The game is paused until the other PC check finishes." },
  cancelled: { ko: "취소했어요.", en: "Cancelled." },
  denied: { ko: "이 창에서는 할 수 없어요.", en: "You can't do that from this window." },
  "bad-request": { ko: "요청 내용이 올바르지 않아요.", en: "The request is not valid." },
  "not-yet": { ko: "아직 지원하지 않아요.", en: "Not supported yet." },
  expired: { ko: "요청 시간이 지났어요. 다시 해 주세요.", en: "The request timed out. Please try again." },
  "no-pet": { ko: "그 개체가 없어요.", en: "That Pokémon isn't there." },
  already: { ko: "이미 그 상태예요.", en: "It's already like that." },
  "already-shiny": { ko: "이미 이로치예요.", en: "It's already shiny." },
  "already-normal": { ko: "이미 일반 색이에요.", en: "It already has its normal colors." },
  "not-pokemon": { ko: "그 칸에 개체가 없어요.", en: "There's no Pokémon in that slot." },
  "not-in-box": { ko: "박스에 없어요.", en: "It's not in the box." },
  "not-in-party": { ko: "파티에 없어요.", en: "It's not in the party." },
  "slot-not-empty": { ko: "그 칸이 이미 차 있어요.", en: "That slot is already taken." },
  "slot-locked": { ko: "잠긴 칸이에요.", en: "That slot is locked." },
  "no-empty-slot": { ko: "파티에 빈 칸이 없어요.", en: "There's no empty party slot." },
  "no-preset": { ko: "그 프리셋이 없어요.", en: "That preset doesn't exist." },
  "already-active": { ko: "이미 쓰고 있는 프리셋이에요.", en: "That preset is already in use." },
  "preset-max": { ko: "더 살 수 있는 프리셋이 없어요.", en: "There are no more presets to buy." },
  "slots-not-full": { ko: "가진 프리셋의 파티 칸을 모두 열어야 해요.", en: "Open every party slot of your presets first." },
  "no-box": { ko: "그 박스를 찾지 못했어요.", en: "Couldn't find that box." },
  "bad-slot": { ko: "그 칸이 없어요.", en: "That slot doesn't exist." },
  "empty-slot": { ko: "그 칸에 개체가 없어요.", en: "There's no Pokémon in that slot." },
  "box-full": { ko: "박스에 빈 칸이 없어요. 자리를 만든 뒤 다시 해 주세요.", en: "There's no empty box slot. Make room, then try again." },
  "same-slot": { ko: "같은 칸으로는 옮길 수 없어요.", en: "You can't move it to the same slot." },
  cooldown: { ko: "아직 쉬는 시간이에요.", en: "It's still resting." },
  full: { ko: "이미 배가 불러요.", en: "It's already full." },
  "no-item": { ko: "가방에 없어요.", en: "It's not in your bag." },
  "none-left": { ko: "가방에 남은 것이 없어요.", en: "There's none left in your bag." },
  "max-level": { ko: "이미 최고 레벨이에요.", en: "It's already at the max level." },
  "bad-nature": { ko: "쓸 수 없는 성격이에요.", en: "That nature can't be used." },
  "no-egg": { ko: "그 알이 없어요.", en: "That egg isn't there." },
  "not-ready": { ko: "아직 준비되지 않았어요.", en: "It's not ready yet." },
  "no-candidate": { ko: "지금은 진화할 수 없어요.", en: "It can't evolve right now." },
  "no-product": { ko: "그 상품이 없어요.", en: "That item isn't for sale." },
  "not-enough-points": { ko: "포인트가 모자라요.", en: "Not enough points." },
  "daycare-full": { ko: "돌보미집이 가득 찼어요.", en: "The daycare is full." },
  "bag-full": { ko: "한 종류는 999개까지만 살 수 있어요.", en: "You can buy up to 999 of one kind." },
  "no-locked-slot": { ko: "더 열 수 있는 칸이 없어요.", en: "There are no more slots to open." },
  "box-max": { ko: "더 살 수 있는 박스가 없어요.", en: "There are no more boxes to buy." },
  "not-unlocked": { ko: "아직 해금하지 않은 종이에요.", en: "That species isn't unlocked yet." },
  "sold-out": { ko: "이 알에서 나올 포켓몬을 모두 모았어요.", en: "You've collected every Pokémon from this egg." },
  "not-sellable": { ko: "팔 수 없는 도구예요.", en: "That item can't be sold." },
  "not-enough-items": { ko: "가진 개수보다 많이 팔 수 없어요.", en: "You can't sell more than you have." },
  "pet-not-sellable": { ko: "팔 수 없는 포켓몬이에요.", en: "That Pokémon can't be sold." },
  "trade-locked": { ko: "교환에 올린 포켓몬이에요. 교환을 끝내거나 나간 뒤 다시 해 주세요.", en: "That Pokémon is up for trade. Finish or leave the trade, then try again." },
  "last-pet": { ko: "마지막 한 마리는 팔 수 없어요.", en: "You can't sell your last Pokémon." },
  "in-preset": { ko: "파티에 든 포켓몬은 팔 수 없어요. 박스로 옮긴 뒤 팔아 주세요.", en: "Pokémon in a party can't be sold. Move it to the box first." },
  "no-step": { ko: "더 진화하지 않아요.", en: "It doesn't evolve any further." },
  "need-choice": { ko: "진화할 모습을 골라 주세요.", en: "Choose the form to evolve into." },
  "bad-choice": { ko: "고른 모습으로는 지금 진화할 수 없어요.", en: "It can't evolve into that form right now." },
  "no-map": { ko: "지도가 있어야 이 모습으로 진화해요.", en: "A map is needed to evolve into this form." },
  "not-shared": { ko: "모습을 바꿀 수 없는 포켓몬이에요.", en: "This Pokémon can't change its look." },
  "bad-form": { ko: "고를 수 없는 모습이에요.", en: "That form can't be chosen." },
  "form-locked": { ko: "아직 열리지 않은 모습이에요.", en: "That form isn't unlocked yet." },
  "no-rider": { ko: "그 모습이 되려면 말이 있어야 해요.", en: "That form needs its steed." },
  "not-rider-owner": { ko: "버드렉스가 있어야 쓸 수 있어요.", en: "You need a Calyrex to use this." },
  "no-stone": { ko: "메가스톤이 없어요.", en: "It has no Mega Stone." },
  "art-missing": { ko: "바뀔 모습의 그림을 받지 못했어요. 잠시 뒤 다시 해 주세요.", en: "Couldn't get the new form's art. Please try again later." },
  "no-achievement": { ko: "그 업적이 없어요.", en: "That achievement doesn't exist." },
  "not-achieved": { ko: "아직 달성하지 않았어요.", en: "Not achieved yet." },
  "already-claimed": { ko: "이미 받았어요.", en: "Already claimed." },
  "egg-none": { ko: "이 알에서 나올 포켓몬을 모두 모았어요.", en: "You've collected every Pokémon from this egg." },
  "bad-id": { ko: "알 수 없는 항목이에요.", en: "Unknown item." },
  "trade-not-ready": { ko: "아직 확정할 수 없어요. 두 사람 모두 포켓몬을 올려야 확정할 수 있어요.", en: "You can't confirm yet. Both of you need to offer a Pokémon first." },
  busy: { ko: "잠시 뒤에 다시 해 주세요. 앞의 조작을 처리하는 중이에요.", en: "Please try again in a moment. The previous action is still being handled." },
  "no-channel": { ko: "교환을 찾지 못했어요. 새 링크로 다시 시작해 주세요.", en: "Couldn't find the trade. Start again with a new link." },
  "in-trade": { ko: "진행 중인 교환이 있어요. 지금 교환에서 나간 뒤 다시 해 주세요.", en: "A trade is in progress. Leave it, then try again." },
  stopped: { ko: "교환이 멈췄어요. 새 링크로 다시 시작해 주세요.", en: "The trade stopped. Start again with a new link." },
  "cloud-wait": { ko: "클라우드 저장이 연결되지 않았어요. 연결되면 다시 해 주세요. 계정 탭에서 저장 상태를 볼 수 있어요.", en: "Cloud save isn't connected. Try again once it connects. You can check it in the Account tab." },
  "login-required": { ko: "로그인해야 교환할 수 있어요. 계정 탭에서 로그인해 주세요.", en: "You need to sign in to trade. Sign in from the Account tab." },
  "save-wait": { ko: "아직 저장되지 않은 포켓몬이에요. 저장이 끝나면 다시 올려 주세요.", en: "That Pokémon isn't saved yet. Offer it again once saving finishes." },
  single: { ko: "단일 포켓몬이라 교환할 수 없어요.", en: "Single Pokémon can't be traded." },
  locked: { ko: "교환에 올린 포켓몬이에요. 교환을 끝내거나 나간 뒤 다시 해 주세요.", en: "That Pokémon is up for trade. Finish or leave the trade, then try again." },
  "bad-received": { ko: "받은 포켓몬의 정보가 올바르지 않아요.", en: "The received Pokémon's data is not valid." },
  "trade-off": { ko: "지금은 교환을 쓸 수 없어요.", en: "Trading isn't available right now." },
  "bad-gift": { ko: "앱을 업데이트하면 받을 수 있어요.", en: "Update the app to receive it." },
  CLOUD_ACCOUNT_HELD: { ko: "이 계정은 이용이 정지됐어요.", en: "This account has been suspended." },
  CLOUD_BAD_ARGS: { ko: "계정 저장 요청이 올바르지 않아요.", en: "The cloud save request is not valid." },
  CLOUD_EMPTY_SAVE: { ko: "계정에 저장된 진행이 없어요.", en: "There's no progress saved to this account." },
  CLOUD_HANDOFF_INVALID: { ko: "이 PC 진행을 계정으로 옮기지 못했어요.", en: "Couldn't move this PC's progress to the account." },
  CLOUD_LOGIN_REQUIRED: { ko: "다시 로그인해 주세요.", en: "Please sign in again." },
  CLOUD_NOT_ACTIVE: { ko: "이 PC 는 지금 계정 저장을 맡고 있지 않아요.", en: "This PC isn't handling the account save right now." },
  CLOUD_PET_TRADED_OUT: { ko: "교환으로 보낸 포켓몬이 남아 있어 올리지 않아요.", en: "Not uploaded because a traded-away Pokémon is still here." },
  CLOUD_REV_CONFLICT: { ko: "다른 PC 의 저장이 더 새로워요. 다시 받아 온 뒤 해 주세요.", en: "Another PC has a newer save. Get it first, then try again." },
  CLOUD_SAVE_REJECTED: { ko: "서버가 저장을 받지 않았어요.", en: "The server didn't accept the save." },
  CLOUD_TOO_LARGE: { ko: "저장이 너무 커서 올리지 못했어요.", en: "The save is too large to upload." },
  CLOUD_TRADE_ACTIVE: { ko: "다른 PC 에서 교환 중이라 넘겨받을 수 없어요.", en: "Can't take over while another PC is trading." },
  CLOUD_TRADE_UNSYNCED: { ko: "다른 PC 에서 끝낸 교환이 아직 저장되지 않았어요.", en: "A trade finished on another PC isn't saved yet." },
  CLOUD_UPDATE_REQUIRED: { ko: "업데이트해야 계정에 저장돼요.", en: "Update the app to save to your account." },
  TRADE_AUTH_REQUIRED: { ko: "로그인해야 교환할 수 있어요. 계정 탭에서 로그인해 주세요.", en: "You need to sign in to trade. Sign in from the Account tab." },
  TRADE_BAD_ARGS: { ko: "교환 요청이 올바르지 않아요.", en: "The trade request is not valid." },
  TRADE_VERSION_MISMATCH: { ko: "앱 버전이 달라요. 두 사람 모두 앱을 업데이트해 주세요.", en: "Your app versions differ. Both of you, please update the app." },
  TRADE_RATE_LIMITED: { ko: "잠시 뒤에 다시 해 주세요. 짧은 시간에 링크를 너무 많이 만들었어요.", en: "Please try again later. Too many links were made in a short time." },
  TRADE_ALREADY_ACTIVE: { ko: "진행 중인 교환이 있어요. 지금 교환에서 나간 뒤 다시 해 주세요.", en: "A trade is in progress. Leave it, then try again." },
  TRADE_LINK_INVALID: { ko: "링크가 올바르지 않아요. 친구가 보낸 링크를 그대로 붙여 넣어 주세요.", en: "The link is not valid. Paste the link your friend sent as is." },
  TRADE_LINK_EXPIRED: { ko: "링크가 만료됐어요. 참가 전 10분이 지났어요. 친구에게 새 링크를 받아 주세요.", en: "The link expired. 10 minutes passed before joining. Ask your friend for a new link." },
  TRADE_LINK_USED: { ko: "이미 사용된 링크예요. 다른 사람이 먼저 참가했어요.", en: "That link was already used. Someone else joined first." },
  TRADE_OWN_LINK: { ko: "내가 만든 링크예요. 친구에게 보내 주세요.", en: "That's your own link. Send it to your friend." },
  TRADE_NOT_FOUND: { ko: "교환을 찾지 못했어요. 새 링크로 다시 시작해 주세요.", en: "Couldn't find the trade. Start again with a new link." },
  TRADE_CLOSED: { ko: "친구가 교환을 닫았어요. 새 링크로 다시 시작해 주세요.", en: "Your friend closed the trade. Start again with a new link." },
  TRADE_OFFER_INVALID: { ko: "올릴 수 없는 포켓몬이에요. 다른 포켓몬을 골라 주세요.", en: "That Pokémon can't be offered. Choose another one." },
  TRADE_OFFER_MISSING: { ko: "아직 올린 포켓몬이 없어요.", en: "No Pokémon has been offered yet." },
  TRADE_OFFER_CHANGED: { ko: "올린 포켓몬이 바뀌었어요. 다시 확인해 주세요.", en: "The offered Pokémon changed. Please check again." },
  TRADE_ALREADY_DONE: { ko: "이미 끝난 교환이에요.", en: "That trade is already finished." },
  TRADE_NOT_DONE: { ko: "아직 끝나지 않은 교환이에요.", en: "That trade isn't finished yet." },
  TRADE_LOGIN_REQUIRED: { ko: "로그인해야 교환할 수 있어요. 계정 탭에서 로그인해 주세요.", en: "You need to sign in to trade. Sign in from the Account tab." },
  TRADE_PET_TRADED: { ko: "이미 교환으로 보낸 포켓몬이에요. 다른 포켓몬을 골라 주세요.", en: "That Pokémon was already traded away. Choose another one." },
  TRADE_PET_NOT_SYNCED: { ko: "아직 저장되지 않은 포켓몬이에요. 저장이 끝나면 다시 올려 주세요.", en: "That Pokémon isn't saved yet. Offer it again once saving finishes." },
  TRADE_PET_BUSY: { ko: "다른 교환에 올라가 있는 포켓몬이에요. 그 교환이 닫힌 뒤 다시 올리거나 다른 포켓몬을 골라 주세요.", en: "That Pokémon is in another trade. Offer it after that trade closes, or choose another one." },
  TRADE_SAVE_UNVERIFIED: { ko: "이 계정은 교환할 수 없어요. 계정 저장 확인이 필요해요.", en: "This account can't trade. The account save needs a review." },
  MAIL_EXPIRED: { ko: "기간이 지나 받을 수 없어요.", en: "It has expired and can't be received." },
  MAIL_LOGIN_REQUIRED: { ko: "로그인하면 받을 수 있어요.", en: "Sign in to receive it." },
  MAIL_NO_GIFTS: { ko: "받을 선물이 없어요.", en: "There are no gifts to receive." },
  MAIL_NOT_FOUND: { ko: "편지를 찾지 못했어요.", en: "Couldn't find the letter." },
  AUTH_NAME_INVALID: { ko: `이름은 1~${AR.nameMax}자로 적어 주세요.`, en: `Names must be 1–${AR.nameMax} characters.` },
  AUTH_USERNAME_INVALID: { ko: `아이디는 영문 소문자로 시작하고 소문자·숫자·_ ${AR.usernameMin}~${AR.usernameMax}자예요.`, en: `Usernames start with a lowercase letter and use ${AR.usernameMin}–${AR.usernameMax} lowercase letters, digits, or _.` },
  AUTH_USERNAME_RESERVED: { ko: "이미 쓰는 아이디예요.", en: "That username is taken." },
  AUTH_ANONYMOUS: { ko: "익명 계정으로는 할 수 없어요. 로그인해 주세요.", en: "You can't do this with an anonymous account. Please sign in." },
  AUTH_REQUIRED: { ko: "로그인해야 해요. 계정 탭에서 로그인해 주세요.", en: "You need to sign in. Sign in from the Account tab." },
  AUTH_TOKEN: { ko: "다시 로그인해 주세요.", en: "Please sign in again." },
  AUTH_TRADE_ACTIVE: { ko: "교환 중에는 계정을 바꿀 수 없어요.", en: "You can't change accounts during a trade." },
  NETWORK: { ko: "서버에 연결할 수 없어요. 잠시 뒤 다시 해 주세요.", en: "Can't reach the server. Please try again later." },
  UNKNOWN: { ko: "알 수 없는 오류예요. 잠시 뒤 다시 해 주세요.", en: "Unknown error. Please try again later." },
  LOCAL: { ko: "이 PC 에서 교환을 반영하지 못했어요.", en: "Couldn't apply the trade on this PC." },
  CLOUD_OWNER_OTHER: { ko: "이 PC 진행은 다른 계정 것이라 올리지 않아요.", en: "Not uploaded because this PC's progress belongs to another account." },
  CLOUD_BAD_SAVE: { ko: "계정 저장을 읽지 못해 올리지 않아요.", en: "Not uploaded because the account save couldn't be read." },
  AUTH_INVALID_LOGIN: { ko: "아이디 또는 비밀번호가 맞지 않아요.", en: "Wrong username or password." },
  AUTH_USERNAME_TAKEN: { ko: "이미 쓰는 아이디예요.", en: "That username is taken." },
  AUTH_PASSWORD_WEAK: { ko: `비밀번호는 ${AR.passwordMin}자 이상이에요.`, en: `Passwords must be at least ${AR.passwordMin} characters.` },
  AUTH_RATE_LIMITED: { ko: "잠시 뒤에 다시 해 주세요.", en: "Please try again later." },
  AUTH_CANCELLED: { ko: "로그인을 취소했어요.", en: "Sign-in was cancelled." },
  AUTH_PORT_BUSY: { ko: "로그인 창을 열 수 없어요. 잠시 뒤에 다시 해 주세요.", en: "Can't open the sign-in window. Please try again later." },
  SAVE_BACKUP_FAILED: { ko: "이 PC 저장을 백업하지 못해 새로 시작하지 않았어요.", en: "Didn't start fresh because this PC's save couldn't be backed up." },
};

// 표에 없는 글자가 왔을 때 — 자리마다 지금 모양
const UNKNOWN: Record<FailScope, (code: string) => { text: string; detail?: string }> = {
  command: (code) => ({ text: code }),
  trade: (code) => ({ text: "교환을 진행하지 못했어요", detail: `잠시 뒤에 다시 해 주세요 (${code})` }),
  account: (code) => ({ text: `계정 작업을 하지 못했어요 (${code})` }),
  mail: (code) => ({ text: `받지 못했어요 (${code})` }),
};

const isFailCode = (code: string): code is FailCode => Object.prototype.hasOwnProperty.call(FAIL_TEXT, code);

// 실패 값의 문구 — 교환만 둘째 줄(detail)이 있다. 교환 배너의 두 줄은 마침표 없이 보인다(지금 모양)
// detail — 목록 밖 서버 코드를 UNKNOWN 으로 접은 곳이 넘기는 원래 글자. 있으면 표에 없는 글자처럼 괄호에 그 글자를 보인다 (94 항목 5-4, 계약 레인 부탁)
export function failTextOf(code: FailCode | string, scope: FailScope, lang: FailLang = "ko", detail?: string): { text: string; detail?: string } {
  if (!isFailCode(code)) return UNKNOWN[scope](code);
  if (code === "UNKNOWN" && detail) return UNKNOWN[scope](detail);
  const text = FAIL_TEXT[code][lang];
  if (scope !== "trade") return { text };
  const cut = text.search(/[.?!] /);
  const head = (cut < 0 ? text : text.slice(0, cut + 1)).replace(/[.]$/, "");
  const rest = cut < 0 ? "" : text.slice(cut + 2).replace(/[.]$/, "");
  return rest ? { text: head, detail: rest } : { text: head };
}
